int32 boom_angle_sensor_angle

int32 wind_sensor_0_speed
int32 wind_sensor_0_direction
int32 wind_sensor_0_reference
int32 wind_sensor_1_speed
int32 wind_sensor_1_direction
int32 wind_sensor_1_reference
int32 wind_sensor_2_speed
int32 wind_sensor_2_direction
int32 wind_sensor_2_reference

string   gps_0_timestamp
float32  gps_0_latitude
float32  gps_0_longitude
bool     gps_0_latitude_loc
bool     gps_0_longitude_loc
int32    gps_0_groundspeed
int32    gps_0_track_made_good
int32    gps_0_magnetic_variation
bool     gps_0_magnetic_variation_sense
string   gps_1_timestamp
float32  gps_1_latitude
float32  gps_1_longitude
bool     gps_1_latitude_loc
bool     gps_1_longitude_loc
int32    gps_1_groundspeed
int32    gps_1_track_made_good
int32    gps_1_magnetic_variation
bool     gps_1_magnetic_variation_sense

int32 accelerometer_x_axis_acceleration
int32 accelerometer_y_axis_acceleration
int32 accelerometer_z_axis_acceleration
